name: temple_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.4.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  get: ^4.6.6
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  kf_drawer: ^1.2.1
  connectivity_plus: ^6.1.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  animated_custom_dropdown: ^3.1.1
  carousel_slider: ^5.0.0
  rounded_tabbar_widget: ^0.0.2
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  easy_localization: ^3.0.7
  shimmer: ^3.0.0
  riverpod_annotation: ^2.6.1
  dio: ^5.7.0
  lottie: ^3.1.3
  logger: ^2.5.0
  http: ^1.1.0
  fluttertoast: ^8.2.5
  hive: ^2.2.3
  excel: ^4.0.6
  file_picker: ^5.4.1
  path_provider: ^2.1.0
  hive_flutter: ^1.1.0
  go_router: ^14.6.2
  geocode: ^1.0.3
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/

flutter_gen:
  output: lib\src\core\assets\
